version: '3'
services:
 app:
   build:
     context: .
     dockerfile: docker/app/Dockerfile
   env_file:
     - .env
   volumes:
     - .:/usr/src/app
   depends_on:
     - db
 db:
   image: mysql:5.7.23
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   env_file:
     - .env
   ports:
     - "33061:3306"
   volumes:
     - db-data:/var/lib/mysql
 web:
   build:
     context: .
     dockerfile: ./docker/web/Dockerfile
   ports:
     - 8080:80
   depends_on:
     - app
volumes:
 db-data:
